#!/usr/bin/env node

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SRC_DIR = join(__dirname, 'src');
const DIST_DIR = join(__dirname, 'dist');

// Load all token files
function loadTokens() {
  const tokens = {};
  const files = readdirSync(SRC_DIR).filter(f => f.endsWith('.json'));

  for (const file of files) {
    const content = JSON.parse(readFileSync(join(SRC_DIR, file), 'utf-8'));
    Object.assign(tokens, content);
  }

  return tokens;
}

// Resolve token references like {colors.primitive.beige-100}
function resolveReferences(obj, allTokens) {
  const refRegex = /\{([^}]+)\}/g;

  function getValue(path) {
    const keys = path.split('.');
    let ref = allTokens;
    for (const key of keys) {
      ref = ref?.[key];
    }
    return ref?.$value;
  }

  function resolveValue(value) {
    if (typeof value !== 'string') return value;
    return value.replace(refRegex, (match, path) => {
      const resolved = getValue(path);
      return resolved !== undefined ? resolved : match;
    });
  }

  const resolved = {};
  for (const [key, value] of Object.entries(obj)) {
    if (value?.$value !== undefined) {
      resolved[key] = {
        ...value,
        $value: resolveValue(value.$value)
      };
    } else if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      resolved[key] = resolveReferences(value, allTokens);
    } else {
      resolved[key] = value;
    }
  }

  return resolved;
}

// Flatten nested tokens to CSS variable format
function flattenToCSSVars(obj, prefix = '') {
  const result = {};

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue; // Skip meta properties

    const varName = prefix ? `${prefix}-${key}` : key;

    if (value?.$value !== undefined) {
      let cssValue = value.$value;
      // Handle arrays (font families)
      if (Array.isArray(cssValue)) {
        cssValue = cssValue.map(v => v.includes(' ') ? `"${v}"` : v).join(', ');
      }
      result[varName] = cssValue;
    } else if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenToCSSVars(value, varName));
    }
  }

  return result;
}

// Generate CSS custom properties
function generateCSS(tokens) {
  const resolved = resolveReferences(tokens, tokens);
  const flattened = flattenToCSSVars(resolved);

  let css = `/* Auto-generated by @fermindi/retro-tokens. Do not edit. */

:root {
`;

  for (const [key, value] of Object.entries(flattened)) {
    css += `  --${key}: ${value};\n`;
  }

  css += `}
`;

  return css;
}

// Generate Tailwind config
function generateTailwindConfig(tokens) {
  const resolved = resolveReferences(tokens, tokens);

  // Extract specific token categories
  const colors = resolved.colors || {};
  const typography = resolved.typography || {};
  const spacing = resolved.spacing || {};
  const radius = resolved.radius || {};
  const shadow = resolved.shadow || {};

  // Build color object for Tailwind
  function buildColors(colorObj) {
    const result = {};
    for (const [key, value] of Object.entries(colorObj)) {
      if (key.startsWith('$')) continue;
      if (value?.$value !== undefined) {
        result[key] = `var(--colors-${key.includes('primitive') ? 'primitive-' : 'semantic-'}${key})`;
      } else if (typeof value === 'object') {
        const nested = buildColors(value);
        for (const [k, v] of Object.entries(nested)) {
          result[k] = v;
        }
      }
    }
    return result;
  }

  // Semantic colors use CSS vars for theming support
  const semanticColors = {};
  if (colors.semantic) {
    for (const [key, value] of Object.entries(colors.semantic)) {
      if (key.startsWith('$')) continue;
      semanticColors[key] = `var(--colors-semantic-${key})`;
    }
  }

  // Build spacing
  const spacingValues = {};
  for (const [key, value] of Object.entries(spacing)) {
    if (key.startsWith('$')) continue;
    if (value?.$value !== undefined) {
      spacingValues[key] = value.$value;
    }
  }

  // Build radius
  const radiusValues = {};
  for (const [key, value] of Object.entries(radius)) {
    if (key.startsWith('$')) continue;
    if (value?.$value !== undefined) {
      radiusValues[key] = value.$value;
    }
  }

  // Build shadows
  const shadowValues = {};
  for (const [key, value] of Object.entries(shadow)) {
    if (key.startsWith('$')) continue;
    if (value?.$value !== undefined) {
      shadowValues[key] = value.$value;
    }
  }

  // Build font families
  const fontFamily = {};
  if (typography.fontFamily) {
    for (const [key, value] of Object.entries(typography.fontFamily)) {
      if (key.startsWith('$')) continue;
      if (value?.$value !== undefined) {
        fontFamily[key] = value.$value;
      }
    }
  }

  // Build font sizes
  const fontSize = {};
  if (typography.fontSize) {
    for (const [key, value] of Object.entries(typography.fontSize)) {
      if (key.startsWith('$')) continue;
      if (value?.$value !== undefined) {
        fontSize[key] = value.$value;
      }
    }
  }

  const config = `/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: ${JSON.stringify(semanticColors, null, 8).replace(/"/g, "'").replace(/\n/g, '\n      ')},
      fontFamily: ${JSON.stringify(fontFamily, null, 8).replace(/"/g, "'").replace(/\n/g, '\n      ')},
      fontSize: ${JSON.stringify(fontSize, null, 8).replace(/"/g, "'").replace(/\n/g, '\n      ')},
      spacing: ${JSON.stringify(spacingValues, null, 8).replace(/"/g, "'").replace(/\n/g, '\n      ')},
      borderRadius: ${JSON.stringify(radiusValues, null, 8).replace(/"/g, "'").replace(/\n/g, '\n      ')},
      boxShadow: ${JSON.stringify(shadowValues, null, 8).replace(/"/g, "'").replace(/\n/g, '\n      ')},
    },
  },
};
`;

  return config;
}

// Generate CommonJS Tailwind config
function generateTailwindConfigCJS(tokens) {
  const esm = generateTailwindConfig(tokens);
  return esm.replace('export default', 'module.exports =');
}

// Generate TypeScript definitions
function generateTypeDefs(tokens) {
  const resolved = resolveReferences(tokens, tokens);

  return `// Auto-generated by @fermindi/retro-tokens. Do not edit.

export declare const tokens: ${JSON.stringify(resolved, null, 2)};

export default tokens;
`;
}

// Generate JS module with tokens
function generateJSModule(tokens) {
  const resolved = resolveReferences(tokens, tokens);

  return `// Auto-generated by @fermindi/retro-tokens. Do not edit.

export const tokens = ${JSON.stringify(resolved, null, 2)};

export default tokens;
`;
}

// Generate CJS module
function generateCJSModule(tokens) {
  const resolved = resolveReferences(tokens, tokens);

  return `// Auto-generated by @fermindi/retro-tokens. Do not edit.

const tokens = ${JSON.stringify(resolved, null, 2)};

module.exports = { tokens, default: tokens };
`;
}

// Main build function
function build() {
  console.log('Building tokens...');

  if (!existsSync(DIST_DIR)) {
    mkdirSync(DIST_DIR, { recursive: true });
  }

  const tokens = loadTokens();

  // Generate CSS variables
  const css = generateCSS(tokens);
  writeFileSync(join(DIST_DIR, 'variables.css'), css);
  console.log('  ✓ dist/variables.css');

  // Generate Tailwind config
  const tailwindConfig = generateTailwindConfig(tokens);
  writeFileSync(join(DIST_DIR, 'tailwind.config.js'), tailwindConfig);
  console.log('  ✓ dist/tailwind.config.js');

  const tailwindConfigCJS = generateTailwindConfigCJS(tokens);
  writeFileSync(join(DIST_DIR, 'tailwind.config.cjs'), tailwindConfigCJS);
  console.log('  ✓ dist/tailwind.config.cjs');

  // Generate JS module
  const jsModule = generateJSModule(tokens);
  writeFileSync(join(DIST_DIR, 'index.js'), jsModule);
  console.log('  ✓ dist/index.js');

  const cjsModule = generateCJSModule(tokens);
  writeFileSync(join(DIST_DIR, 'index.cjs'), cjsModule);
  console.log('  ✓ dist/index.cjs');

  // Generate TypeScript definitions
  const typeDefs = generateTypeDefs(tokens);
  writeFileSync(join(DIST_DIR, 'index.d.ts'), typeDefs);
  writeFileSync(join(DIST_DIR, 'tailwind.config.d.ts'), `import type { Config } from 'tailwindcss';
declare const config: Partial<Config>;
export default config;
`);
  console.log('  ✓ dist/index.d.ts');
  console.log('  ✓ dist/tailwind.config.d.ts');

  console.log('\nBuild complete!');
}

build();
